apiVersion: lupus.gawor.io/v1
kind: Master
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: lola
spec:
  name: "lola"
  elements:
    - name: "observe1"
      type: observe
      observe:
        next:
          - type: "decide"
            name: "decide1"
            keys: ["*"]
    - name: "decide1"
      type: decide
      decide:
        actions:
          - name: "insert1"
            type: insert
            insert:
              outputKey: "*"
              value: {"log.path_taken": "A"}
            next: "start"
          - name: "insertComplex"
            type: insert
            insert:
              outputKey: "*"
              value: {"elo": "hej", "poland": {
                      "capital": "Warsaw",
                      "population": 38
                    }}
            next: "insert2"
          - name: "insert2"
            type: insert
            insert:
              outputKey: "elo"
              value: {karczycho: 10}
            next: "insert3"
          - name: "insert3"
            type: insert
            insert:
              outputKey: "elo"
              value: {"name": "maria", "age": 12}
            next: "start"
          - name: "start"
            type: print
            print:
              inputKeys: ["*"]
            next: "final"
        next:
          - type: "execute"
            name: "execute1"
            keys: ["*"]
    - name: "execute1"
      type: execute
      execute:
        destination:
          type: "HTTP"
          http:
            path: "http://192.168.56.111:7000/api/command"
            method: "POST"