apiVersion: lupus.gawor.io/v1
kind: Decide
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: adam-decide
spec:
  name: "adam"
  nextElement: "execute"
  opa_url:
    path: "http://192.168.56.111:8181/v1/mmet"
    method: "POST"
