# permissions for end users to view decisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: decision-viewer-role
rules:
- apiGroups:
  - lupus.gawor.io
  resources:
  - decisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lupus.gawor.io
  resources:
  - decisions/status
  verbs:
  - get
