# permissions for end users to view decides.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: decide-viewer-role
rules:
- apiGroups:
  - lupus.gawor.io
  resources:
  - decides
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lupus.gawor.io
  resources:
  - decides/status
  verbs:
  - get
