# permissions for end users to edit monitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: monitor-editor-role
rules:
- apiGroups:
  - lupus.gawor.io
  resources:
  - monitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lupus.gawor.io
  resources:
  - monitors/status
  verbs:
  - get
