---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lupus.gawor.io
  resources:
  - decides
  - executes
  - loops
  - observes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lupus.gawor.io
  resources:
  - decides/finalizers
  - executes/finalizers
  - loops/finalizers
  - observes/finalizers
  verbs:
  - update
- apiGroups:
  - lupus.gawor.io
  resources:
  - decides/status
  - executes/status
  - loops/status
  - observes/status
  verbs:
  - get
  - patch
  - update
