apiVersion: lupus.gawor.io/v1
kind: Master
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: piotrek
spec:
  name: "piotrek"
  elements:
    - name: "observe1"
      type: "Observe"
      observeSpec:
        next:
          - type: "Decide"
            name: "decide1"
            tags: ["*"]
    - name: "decide1"
      type: "Decide"
      decideSpec:
        actions:
          - name: "ram"
            inputTag: "ram"
            destination:
              type: Opa
              http:
                path: "http://192.168.56.111:8181/v1/data/mc_server/ram"
            outputTag: "ram"
          - name: "cpu"
            inputTag: "cpu"
            destination:
              type: "Opa"
              opa:
                path: "http://192.168.56.111:8181/v1/data/mc_server/cpu"
            outputTag: "cpu"
        next:
          - type: "Execute"
            name: "execute1"
            tags: ["*"]
    - name: "execute1"
      type: "Execute"
      executeSpec:
        destination:
          type: "HTTP"
          http:
            path: "http://192.168.56.111:6001/api/commands"
            method: "POST"