apiVersion: lupus.gawor.io/v1
kind: Master
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: olek
spec:
  name: "olek"
  elements:
    - name: "observe1"
      type: observe
      observe:
        next:
          - type: "decide"
            name: "decide1"
            keys: ["*"]
    - name: "decide1"
      type: decide
      decide:
        actions:
          - name: "start"
            type: print
            print:
              inputKeys: ["*"]
          - name: "ram"
            type: send
            send:
              inputKey: "ram"
              destination:
                type: Opa
                opa:
                  path: "http://192.168.56.111:8282/v1/data/mc_server/ram"
              outputKey: "ram"
          - name: "cpu"
            type: send
            send:
              inputKey: "cpu"
              destination:
                type: Opa
                opa:
                  path: "http://192.168.56.111:8282/v1/data/mc_server/cpu"
              outputKey: "cpu"
          - name: "before-concat"
            type: print
            print:
              inputKeys: ["*"]
          - name: "concat"
            type: nest
            nest:
              inputKeys: ["ram", "cpu"]
              outputKey: "commands"
          - name: "after-concat"
            type: print
            print:
              inputKeys: ["*"]
        next:
          - type: "execute"
            name: "execute1"
            keys: ["*"]
    - name: "execute1"
      type: execute
      execute:
        destination:
          type: "HTTP"
          http:
            path: "http://192.168.56.111:6001/api/commands"
            method: "POST"