apiVersion: lupus.gawor.io/v1
kind: Master
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: adam
spec:
  name: "adam"
  elements:
    - name: "observe1"
      type: observe
      observe:
        next:
          - type: decide
            name: "decide1"
            keys: ["*"]
          - type: learn
            name: "learn1"
            keys: ["*"]
    - name: "decide1"
      type: decide
      decide:
        actions:
          - name: "bounce"
            type: send
            send:
              inputKey: "*"
              destination:
                type: HTTP
                http:
                  path: "http://192.168.56.111:7000/api/bounce"
                  method: "POST"
              outputKey: "*"
          - name: "send-to-opa"
            type: send
            send:
              inputKey: "*"
              destination:
                type: "Opa"
                opa:
                  path: "http://192.168.56.111:8181/v1/data/mmet/move_commands"
              outputKey: "commands"
        next:
          - type: execute
            name: "execute1"
            keys: ["*"]
          - type: learn
            name: "learn2"
            keys: ["*"]
    - name: "learn1"
      type: learn
      learn:
        destination:
          type: "FILE"
          file:
            path: "trace.txt"
    - name: "learn2"
      type: learn
      learn:
        destination:
          type: "FILE"
          file:
            path: "trace.txt"
    - name: "execute1"
      type: execute
      execute:
        destination:
          type: "HTTP"
          http:
            path: "http://192.168.56.111:5001/api/commands"
            method: "POST"