apiVersion: lupus.gawor.io/v1
kind: Master
metadata:
  labels:
    app.kubernetes.io/name: lupus
    app.kubernetes.io/managed-by: kustomize
  name: lola
spec:
  name: "lola"
  elements:
    - name: "lola"
      descr: "Temporary general element"
      actions:
        - name: "print"
          type: print
          print:
            inputKeys: ["*"]
          next: exit